#Diese TOML haben wir für GridSearch und RandomSearch benutzt, um die einzelnen Ergebnisse getrennt zu haben, auch wenn es doppelt gemoppelt ist.
[Model]
algorithm = "neural_network"
task = "classification"

[Data]
input_start = 0
input_end = 6
target_column = 7
test_size = 0.2
random_state = 42

[NeuralNetwork]
random_search_iterations = 1000

[NeuralNetwork.InitialParameters]
layer1 = 2
layer2 = 10
layer3 = 1
activation = "relu"
learning_rate = 0.01
epochs = 100
loss_function = "mse"

[NeuralNetwork.SearchSpace]
layer1 = [ 7, 7,]
layer2 = [ 1, 500,]
layer3 = [ 1, 1,]
activation = [ "relu", "tanh", "sigmoid",]
learning_rate = [ 1e-5, 1.0,]
epochs = [ 10, 500,]
loss_function = [ "mse", "bce",]

[NeuralNetwork.TunedParameters]
layer1 = 0
layer2 = 0
layer3 = 0
activation = ""
learning_rate = 0.0
epochs = 0
loss_function = ""

[NeuralNetwork.GridSearchParameters]
activation = "tanh"
epochs = 437
layer1 = 7
layer2 = 435
layer3 = 1
learning_rate = 0.02329951810515373
loss_function = "mse"

[NeuralNetwork.RandomSearchParameters]
loss_function = "mse"
learning_rate = 0.0071968567300115215
layer3 = 1
layer2 = 373
layer1 = 7
epochs = 498
activation = "tanh"
