[Model]
algorithm = "neural_network"
task = "classification"

[Data]
input_start = 0
input_end = 6
target_column = 7
test_size = 0.2
random_state = 42

[NeuralNetwork.InitialParameters]
layer1 = 2
layer2 = 10
layer3 = 1
activation = "relu"
learning_rate = 0.01
epochs = 100
loss_function = "mse"

[NeuralNetwork.SearchSpace]
layer1 = [ 2, 2,]
layer2 = [ 1, 100,]
layer3 = [ 1, 1,]
activation = [ "relu", "tanh", "sigmoid",]
learning_rate = [ 0.001, 0.01,]
epochs = [ 100, 2000,]
loss_function = [ "mse", "bce",]

[NeuralNetwork.TunedParameters]
layer1 = 2
layer2 = 70
layer3 = 1
activation = "tanh"
learning_rate = 0.005239840452939109
epochs = 758
loss_function = "mse"
