[Model]
algorithm = "svm"
task = "classification"

[Data]
input_start = 0
input_end = 6
target_column = 7
test_size = 0.2
random_state = 42

[SVM.InitialParameters]
C = 1.0
kernel = "rbf"
gamma = "scale"

[SVM.SearchSpace]
C = [ 0.01, 100.0,]
kernel = [ "linear", "rbf", "poly", "sigmoid",]
gamma = [ "scale", "auto",]

[SVM.TunedParameters]
C = 37.19571013508521
kernel = "rbf"
gamma = "scale"

[SVM.GridSearchParameters]
C = 25.0075
gamma = "scale"
kernel = "rbf"
