[Model]
algorithm = "neural_network"
task = "classification"

[Data]
input_start = 0
input_end = 6
target_column = 7
test_size = 0.2
random_state = 42

[NeuralNetwork.InitialParameters]
layer1 = 2
layer2 = 10
layer3 = 1
activation = "relu"
learning_rate = 0.01
epochs = 100
loss_function = "mse"

[NeuralNetwork.SearchSpace]
layer1 = [ 7, 7,]
layer2 = [ 1, 500,]
layer3 = [ 1, 1,]
activation = [ "relu", "tanh", "sigmoid",]
learning_rate = [ 1e-5, 1.0,]
epochs = [ 10, 500,]
loss_function = [ "mse", "bce",]

[NeuralNetwork.TunedParameters]
layer1 = 7
layer2 = 231
layer3 = 1
activation = "relu"
learning_rate = 0.01
epochs = 398
loss_function = "mse"
