[meta]
status = "response"
data_path = "ExampleCSVBanana.csv"
selected_algorithm = "RandomForest"

[meta.dataset_signature]
dataset_id = "unknown"
domain = "General"
n = 6400
p = 7
dimensionality_ratio = 0.00109375
skewness_mean = "0.07994769826979449"
mean_kurtosis = "-0.1617447611332707"
mean_skewness = "0.07994769826979449"
sparsity = "0.0"
num_to_cat_ratio = inf
missing_density = "0.0"
max_missing_col_pct = "0.0"
class_imbalance_ratio = "1.0031298904538342"
class_entropy = "0.6931459598563237"

[model_to_tune.RandomForest]
n_estimators = [ 100, 200, 500,]
max_depth = [ "None", 10, 20, 30,]

[model_tuned.RandomForest]
n_estimators = 200
max_depth = "None"
accuracy = 0.97625
